- name: Browse a directory recursively
  hosts: all
  gather_facts: true
#  become: yes
#  become_user: root
  tasks:
    - name: Browse a directory recursively
      shell:
        "echo {{ansible_env.PATH}} ; find {{browse_dir}} -type d ! -perm -o+r -prune -o -exec ls -ld {} + > /tmp/ansible-out.txt ; cat /tmp/ansible-out.txt "
 
      register: browsedir
      tags: browsedir

    - debug: msg="{{browsedir.stdout}}"
