- name: Add a user
  hosts: all
  gather_facts: false
#  become: yes
#  become_user: admin
  tasks:
  - name: Ensure the user id is absent
    win_user:
      name: "{{user_name}}"
      state: absent
    
  - name: Add User
    win_user:
      name: "{{user_name}}"
      password: "1qazxsw2"
      state: present
      groups:
        - Users
