- name: Ansible Copy files from Local to Remote
  hosts: all
  gather_facts: false
  tasks:
    - name: copying file with playbook
      copy:
        src: "{{source_file}}"
        dest: "{{dest_dir}}"
        owner: ans
        group: ans       
        mode: 0644

- name: Just ensuring the repo checkout exists
  ansible.builtin.git:
    repo: 'https://github.com/forthkuo/ansible/tree/main/files/config.txt'
    dest: /srv/checkout
    update: no

#- name: creates users files
#      file:
#        path: /tmp/ansible-{{ item }}
#        state: touch
#      loop:
#        - 1111
#        - 2222
#        - 3333
