- name: Ansible Copy files from Local to Remote
  hosts: all
  gather_facts: false
  tasks:
    - name: copying file with playbook
      copy:
        src: "{{source_file}}"
        dest: "{{dest_dir}}"
        owner: ans
        group: ans       
        mode: 0644

    - name: Download file and force basic auth
      ansible.builtin.get_url:
        url: https://github.com/forthkuo/ansible/blob/main/files/config.txt
        dest: "{{dest_dir}}"
        mode: 0555
        force_basic_auth: yes

#- name: creates users files
#      file:
#        path: /tmp/ansible-{{ item }}
#        state: touch
#      loop:
#        - 1111
#        - 2222
#        - 3333
