- name: Ansible Copy Example Local to Remote
  hosts: all
  tasks:
    - name: copying file with playbook
      copy:
        src: ansible.cfg
        dest: /tmp
        owner: ans
        group: ans       
        mode: 0644
