- name: Ansible Copy Example Local to Remote
  hosts: all
  gather_facts: false
  tasks:
    - name: copying file with playbook
      copy:
        src: "{{source_file}}"
        dest: /tmp
        owner: ans
        group: ans       
        mode: 0644
