- name: Browse a directory recursively
  hosts: all
  gather_facts: true
#  become: yes
#  become_user: root
  tasks:
    - name: Print out all Ansible environment variables
      debug:
        msg: "{{ansible_os_family}}"
