- name: Run a command
  hosts: all
  gather_facts: false
#  become: yes
#  become_user: root
  tasks:
    - name: Run a command
      shell: "whoami ; find {{ sub_dir }} -type d ! -perm -o+r -prune -o -exec ls -ld {} + > /tmp/ansible-out.txt ; cat /tmp/ansible-out.txt "
      register: runcmd
      tags: runcmd

    - debug: msg="{{runcmd.stdout}}"
