- name: Run a command
  hosts: all
  gather_facts: false
  tasks:
    - name: Run a command
      shell: "whoami ; find /usr -type d ! -perm -o+r -prune -o -exec ls -ld {} + > /tmp/ansible-out.txt ; cat /tmp/ansible-out.txt "
