- name: Run commands
  hosts: all
  gather_facts: false
  
#  become: yes
#  become_user: root

  tasks:
    - name: Run UNIX commands
      shell: "{{run_cmd}}"
      when:
        - ansible_os_family != "Windows"
        
      register: runcmd
      tags: runcmd

    - name: Run Windows commands
      win_shell: "{{run_cmd}}"
      when:
        - ansible_os_family == "Windows"
        
      register: runcmd
      tags: runcmd
      
#    - debug: msg="{{runcmd.stdout}}"
