- name: Run UNIX commands
  hosts: all
  gather_facts: false
#  become: yes
#  become_user: root
  tasks:
    - name: Run UNIX commands
      shell: "{{unix_cmd}}"
      register: unixcmd
      tags: unixcmd

    - debug: msg="{{unixcmd.stdout}}"
