- name: Run UNIX commands
  hosts: all
  gather_facts: false
  
#  become: yes
#  become_user: root

  tasks:
    - name: Run UNIX commands
      shell: "{{unix_cmd}}"
      when:
        - os_type == "unix"
        
      register: unixcmd
      tags: unixcmd

    - name: Run Windows commands
      win_shell: "{{win_cmd}}"
      when:
        - os_type == "windows"
        
      register: wincmd
      tags: wincmd
      
#    - debug: msg="{{unixcmd.stdout}}"
